### ISSUE TITLE
Merge latest code

### ISSUE THREAD

**Issue by Pajamaman** [lovasoa/tidy-html5#1]
It would be nice if we could merge the latest code from htacg/tidy-html5. It's changed quite a bit since this was forked.

**Comment by mojavelinux** [comment]
Not only that, some very important issues have been fixed in Tidy 5.1 that would be really nice to have, including https://github.com/htacg/tidy-html5/issues/158.

**Comment by mojavelinux** [comment]
Starting in 5.0, there's support for inline SVGs as well, which pretty much makes this a showstopper if you have inline SVGs in your document.

**Comment by mojavelinux** [comment]
I submitted PR #2 to address this issue.

The only thing that bothers me is that I had to change the include path to language.h in console/tidy.c to "../src/language.h". I don't understand why this path cannot be resolved otherwise. That's the only change made outside of the enscripten Makefile.

**Comment by mojavelinux** [comment]
The next step is to get a proper npm package descriptor setup so that we can automate the publishing to npmjs.com.
